// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xboxxpkrlsnrkladqiuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhib3h4cGtybHNucmtsYWRxaXVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NDA4NjEsImV4cCI6MjA1ODQxNjg2MX0.XXH4WYAM1ht1VhEziKu6syTLUkvXj7sX-eVs1paYTZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);